### ISSUE TITLE
1.1.1 release to support Django 1.9

### ISSUE THREAD

**Issue by nealtodd** [Bouke/django-airbrake#10]
If this project is still maintained would it be possible to make a 1.1.1 PyPi release that includes 171966e341?

This commit includes a replacement of `request.REQUEST` with `request.POST`.

Django 1.9 removes `request.REQUEST`. The result is that exception logging fails when the application runs into a 500 error:

```
  File "/.../site-packages/airbrake/handlers.py", line 78, in _generate_xml
    for key, value in request.REQUEST.items():
AttributeError: 'WSGIRequest' object has no attribute 'REQUEST'
```

In my case this was causing an `Internal Server Error` message from nginx and no admin 500 error to be logged for the underlying 500 error. (I had to enable gunicorn logging in my logging config to see the above stacktrace and realise django-airbrake was the reason. I then disabled django-airbrake to see the underlying 500 error).

I don't know if the the current master django-airbrake is fully compatible with Django 1.9, or if you intend to officially support Django > 1.6 but a PyPi release would be a useful nonetheless. At the moment I'd have to stop using it or fork it for Django 1.9 projects.

Cheers.

**Comment by Bouke** [comment]
Please let me know if the current master works for you on Django 1.9. I'll push an update to PyPi.

**Comment by Bouke** [comment]
Update pushed in 5fb0dfe07e74fd269823685c33975526f4d1c675. However there might be some issues as I haven't got the time to thoroughly test it.

**Comment by nealtodd** [comment]
Thanks @Bouke. The 1.2.0 release sorts out the reported issue. I'll report back if I come across any other issues under 1.9.
